// =====================================================
// Ticket Class - FROM UML CLASS DIAGRAM
// Attributes: ticketId, qrCodeUrl
// Methods: downloadAsPdf()
// Relationship: Ticket is generated by one Booking (1:1)
// =====================================================

/**
 * Ticket class (from UML Class Diagram)
 * Represents an e-ticket generated after successful booking
 */
export class Ticket {
  private ticketId: string;
  private qrCodeUrl: string;
  private bookingId: string; // 1:1 relationship with Booking
  private ticketNumber: string;
  private qrCodeData: string;
  private isUsed: boolean;
  private usedAt?: Date;

  constructor(
    ticketId: string,
    bookingId: string,
    ticketNumber: string,
    qrCodeUrl: string = '',
    qrCodeData: string = '',
    isUsed: boolean = false
  ) {
    this.ticketId = ticketId;
    this.bookingId = bookingId;
    this.ticketNumber = ticketNumber;
    this.qrCodeUrl = qrCodeUrl;
    this.qrCodeData = qrCodeData;
    this.isUsed = isUsed;
  }

  /**
   * UC10 - Print E-Ticket
   * Generates and downloads the ticket as a PDF file
   * @returns Path or URL to the generated PDF
   */
  async downloadAsPdf(): Promise<string> {
    // Implementation in TicketService
    // Uses pdfkit library to generate PDF
    // Returns download URL or file path
    return '';
  }

  /**
   * Mark ticket as used
   */
  markAsUsed(): void {
    this.isUsed = true;
    this.usedAt = new Date();
  }

  // Getters
  getTicketId(): string {
    return this.ticketId;
  }

  getBookingId(): string {
    return this.bookingId;
  }

  getTicketNumber(): string {
    return this.ticketNumber;
  }

  getQrCodeUrl(): string {
    return this.qrCodeUrl;
  }

  getQrCodeData(): string {
    return this.qrCodeData;
  }

  getIsUsed(): boolean {
    return this.isUsed;
  }

  getUsedAt(): Date | undefined {
    return this.usedAt;
  }

  // Setters
  setQrCodeUrl(url: string): void {
    this.qrCodeUrl = url;
  }

  setQrCodeData(data: string): void {
    this.qrCodeData = data;
  }
}
